### ISSUE TITLE
Exercise 10 -- Email and URL format validation

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#10]

**Comment by yuktikhurana** [comment]
Please correct the regex for url. 
Also add the regex for email.

**Comment by segunadeleye** [comment]
#### Fixed!!!
- Corrected the regex for url validation.
- Added the regex for email validation.

**Comment by yuktikhurana** [comment]
Please go through regex once again. The regex are incorrect. I typed http://www.google....com for url and _ab@b...c for email and the form got submitted.

**Comment by segunadeleye** [comment]
Regexes for url and email validation have been updated.

**Comment by yuktikhurana** [comment]
looks good
