### ISSUE TITLE
Exercise 12 -- domain/subdomain matching

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#12]
https://github.com/segunadeleye/js_track/blob/master/Ex12/exercise_12.js

**Comment by Shruti2791** [comment]
1) Why do we need to have a load eventListener inside the prototype ?
2) Any specific need for having eventListener on 'load' ? 
3) Inappropriate name 'ExtractURL' . We are not extracting the url rather extracting domain and subdomain out of it.
4) Make 1 regex to find both domain and subdomain.
5) if I enter something like www.google.com then also the program should respond with 

##### Domain: google.com

as this is also a valid URL.

**Comment by segunadeleye** [comment]
#### Fixed!!!
- load event handler moved outside prototype.
- I updated the regex.
- I changed class name to Domain.
- Code now works for www.example.com.

**Comment by segunadeleye** [comment]
- I used the back reference method to extract domain with just on regex.
- I added a init() method to the Domain class.

**Comment by Shruti2791** [comment]
Make changes as Discussed.

**Comment by segunadeleye** [comment]
Issues have been fixed.

**Comment by Shruti2791** [comment]
Code looks good but if I am entering 'www.subsub.subvinsol.vinsol.com' then it should result as :
domain : vinsol.com
subdomain:  subsub.subvinsol

**Comment by segunadeleye** [comment]
Issues fixed

**Comment by Shruti2791** [comment]
looks good :+1:
