### ISSUE TITLE
Exercise 3 -- Maximum 3 checkbox selected

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#3]

**Comment by jatin-baweja** [comment]
1. Construct message using slice for checkedValue so that it does not need to be changed if we change the limit.
2. While fetching checkboxes, you can fetch checked checkboxes by passing a different selector to querySelectorAll()
3. Please use semi-colon to terminate each line.

**Comment by segunadeleye** [comment]
#### Fixed.
- I used a different selector for checked checkboxes (`:checked`).
- I really do not understand how to use slice for constructing the message. Nevertheless, I created a `MessageComposer` class to construct the message.
- Missing semi-colon added.

**Comment by segunadeleye** [comment]
#### Fixed

I added the `composeMessage()` method to the ChildrenCheck class.
