### ISSUE TITLE
Exercise 4 -- Parent Checkbox and their children checkbox colors, movies, drinks and bikes

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#4]

**Comment by jatin-baweja** [comment]
1. Set `display:  none` property for sibling div outside the for loop.
2. Use selector for traversing on only the children input checkboxes when checking/unchecking the children input checkboxes.
3. Store `childCheckbox.length` property in a variable for using it in the for loop

**Comment by segunadeleye** [comment]
##### Fixed!!!
- I used a different selector `document.querySelectorAll('div.className input')` for the children inputs.
- I created a function `check()` within the `ChildrenCheck` class to check/uncheck child checkboxes.
- I moved `display: none` property outside the `for` loop.

**Comment by segunadeleye** [comment]
##### Fixed!!!

I changed the function `check()` to a method `markCheckBoxes()` for the `ChildrenCheck` class.
