### ISSUE TITLE
Exercise 5 -- Dynamic Table ­add rows, edit and delete existing rows

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#5]

**Comment by Shruti2791** [comment]
1) Break the long methods into smaller methods.
2) There is a lot of code repetition. Create separate methods for creating 'td', 'a' elements etc.
3) Pull out the validation code from Table class.
#Need to discuss.

**Comment by segunadeleye** [comment]
#### Fixed.
- Broken long codes into methods. They are at the base of the class methods.
- validator is already an object of the class validate https://github.com/segunadeleye/js_track/blob/master/Validate.js

**Comment by Shruti2791** [comment]
1) Why do we have orphan functions (eg : createTableData and createLink) ? Can't they be encapsulated in their appropriate class.
2) Why should editRow , deleteRow and submit should be a part of table class ? (Let's discuss)
3) The validation logic should not be inside table. Just try and call a method validate which accepts name and email and returns the response. You can then perform your action accordingly.
4) The logic for creating columns(or tds' )should be extracted out from the addRow method. This would make the function smaller and would increase readability.
5) I think the submit and edit functions can be merged. The submit button is creating labels for the given values while edit is creating text field for the given values. Replacing links with button.
6) Try not to hit the DOM much.

**Comment by segunadeleye** [comment]
#### Partially Fixed!!!
- All orphan functions have been encapsulated into the appropriate classes.
- Although submit and edit functions are not together.

**Comment by Shruti2791** [comment]
Make corrections as discussed.

**Comment by segunadeleye** [comment]
#### Fixed!!!

Corrections made.
- I added row object as a property of the Table class and cell object as a property of the Row class.
- I moved the addRow() (renamed as add()) method to the Row class and the append() method to the Cell class.
- I renamed the methods in the Row class.
- I added a removeChildNodes() method to the Cell class.

**Comment by Shruti2791** [comment]
Make changes as discussed

**Comment by segunadeleye** [comment]
Issues fixed.

**Comment by Shruti2791** [comment]
I am closing this issue but make the minor changes discussed.
