### ISSUE TITLE
Exercise 6 -- Form validation using js

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#6]

**Comment by abhishekjain16** [comment]
Feedback:
1. onsubmit="validation.checkValue('form')" should not be there in html, Bind an event on submit in JS itself, which calls checkValue.
2. Question says, check for each field individually, here we have if else ladder, this would check only one field which fails first. Please correct this

**Comment by segunadeleye** [comment]
Fixed!!!

**Comment by abhishekjain16** [comment]
Instead of so many if conditions can we have a method which takes different input values and checks for empty.
Then loop over all inputs and call method.

**Comment by segunadeleye** [comment]
Fixed. But I created a different if condition that has a method to check for length of About Me section.

**Comment by abhishekjain16** [comment]
ok. Accepting this. But We could have extracted loop in some method too.
