### ISSUE TITLE
Exercise 9 -- Move countries from one box to the other

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/js_track#9]

**Comment by yuktikhurana** [comment]
1. use a single method for add/remove
2. Why have you used try catch ? (p.s. please answer this question in your comment)

**Comment by segunadeleye** [comment]
When you click the button of an empty box, the browser logs the error below;

Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

I used try catch so that the error can be ignored.

**Comment by segunadeleye** [comment]
Fixed -- Add/remove now a single function.

I also renamed the class.

**Comment by yuktikhurana** [comment]
1. Can we try to implement this with multiple selections. I might have 100 countries and would wish to move say 20. 20 clicks very difficult. :)
2. We do not need try catch.Can we try figuring out some other way without using try/catch ?

**Comment by segunadeleye** [comment]
#### Fixed!!!
- Multiple selections now implemented.
- `try catch` replaced with if-condition statement

**Comment by yuktikhurana** [comment]
1. Please use appropriate names. For e.g: countries is referring to the source select box, we can use source box instead of start box
2. If condition is not needed now.

**Comment by segunadeleye** [comment]
#### FIxed!!!
- I have changed the variable names.
- if condition has been removed.

**Comment by yuktikhurana** [comment]
Looks Good now :+1:
